spring:
  profiles:
    active: ${activatedProperties}
  flyway:
    enabled: true
    baseline-version: 000
    locations: classpath:db/schema_version
    initOnMigrate: true
    baseline-on-migrate: true
    table: schema_version
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      format_sql: true
      id:
        new_generator_mappings: false
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: dev
    password: demo
    validationQuery: SELECT 1

server:
   port: 8080
   servlet:
      context-path: /blank-api